steps:  
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.2.0:
          folders:
            - tests

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: aws-assume-role-with-web-identity

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.0:
          variables:
            GITHUB_TOKEN: GITHUB_TOKEN
      - ossf-scorecard#v1.0.0:
          github_token: $$GITHUB_TOKEN
