#!/bin/bash

set -euo pipefail

if [[ -z "${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_ROLE_ARN:-}" ]]; then
  echo "🚨 Missing 'role-arn' plugin configuration"
  exit 1
fi

REQUEST_TOKEN_OPTIONAL_ARGS=
ASSUME_ROLE_OPTIONAL_ARGS=
if [[ -n "${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_ROLE_SESSION_DURATION:-}" ]]; then
  REQUEST_TOKEN_OPTIONAL_ARGS="${REQUEST_TOKEN_OPTIONAL_ARGS} --lifetime ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_ROLE_SESSION_DURATION}"
  ASSUME_ROLE_OPTIONAL_ARGS="${ASSUME_ROLE_OPTIONAL_ARGS} --duration-seconds ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_ROLE_SESSION_DURATION}"
fi

echo "~~~ :buildkite::key::aws: Requesting an OIDC token for AWS from Buildkite"

BUILDKITE_OIDC_TOKEN="$(buildkite-agent oidc request-token --audience sts.amazonaws.com ${REQUEST_TOKEN_OPTIONAL_ARGS})"

echo "~~~ :aws: Assuming role using OIDC token"

echo "Role ARN: ${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_ROLE_ARN}"

RESPONSE="$(aws sts assume-role-with-web-identity \
  --role-arn "${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_ROLE_ARN}" \
  --role-session-name "${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_ROLE_SESSION_NAME:-buildkite-job-${BUILDKITE_JOB_ID}}" \
  --web-identity-token "${BUILDKITE_OIDC_TOKEN}" \
  ${ASSUME_ROLE_OPTIONAL_ARGS})"

ASSUME_ROLE_CMD_STATUS=$?
if [[ ${ASSUME_ROLE_CMD_STATUS} -ne 0 ]]; then
  echo "^^^ +++"
  echo "Failed to assume AWS role:"
  echo "${RESPONSE}"
  exit 1
fi

AWS_ACCESS_KEY_ID="$(jq -r ".Credentials.AccessKeyId" <<< "${ASSUME_ROLE_RESPONSE}")"
AWS_SECRET_ACCESS_KEY="$(jq -r ".Credentials.SecretAccessKey" <<< "${ASSUME_ROLE_RESPONSE}")"
AWS_SESSION_TOKEN="$(jq -r ".Credentials.SessionToken" <<< "${ASSUME_ROLE_RESPONSE}")"
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN

echo "Assumed role: $(jq -r .AssumedRoleUser.AssumedRoleId <<< "${RESPONSE}")"

region="${BUILDKITE_PLUGIN_AWS_ASSUME_ROLE_WITH_WEB_IDENTITY_REGION:-}"
if [[ -n $region ]]; then
  export AWS_REGION="$region"
  export AWS_DEFAULT_REGION="$region"
  echo "Using region: ${AWS_REGION}"
fi
